workflows:
    react-native-android:
        name: React native android
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic4"
        scripts:
          - name: Set Android SDK location
            script: | 
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          - name: Install npm dependencies
            script: | 
              npm install
          - name: Install Expo CLI and eject
            script: | 
              npm install -g expo-cli
              expo eject
          - name: Set up app/build.gradle
            script: |
              mv ./support-files/build.gradle android/app     
          - name: Build Android release
            script: |
              LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name 'io.codemagic.dtrdic4')
              if [ -z LATEST_BUILD_NUMBER ]; then
                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
              else
                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
              fi
              cd android
              ./gradlew bundleRelease \
                -PversionCode=$UPDATED_BUILD_NUMBER \
                -PversionName=1.0.$UPDATED_BUILD_NUMBER
        artifacts:
            - android/app/build/outputs/**/*.aab
        publishing:
          email:
            recipients:
              - david@nevercode.com
            notify:
              success: true
              failure: false
          google_play:
            credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
            track: internal
            submit_as_draft: true