workflows:
    react-native-android:
        name: React native android
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic4"
        scripts:
        - name: Install dependencies and Expo CLI, and eject app
          script: |
            yarn install
            yarn global add expo-cli
            expo eject
        - name: Set up app/build.gradle
          script: |
            mv ./support-files/build.gradle android/app
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: | 
            LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
            if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
                UPDATED_BUILD_NUMBER=$BUILD_NUMBER
            else
                UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            fi
            cd android
            ./gradlew bundleRelease \
                -PversionCode=$UPDATED_BUILD_NUMBER \
                -PversionName=1.0.$UPDATED_BUILD_NUMBER
        artifacts:
          - android/app/build/outputs/**/*.aab