workflows:
    sample-workflow:
        name: Android Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - davidKeystore